
auth-server:
  oauth2:
    redirect-url: "https://oidcdebugger.com/debug"
    client-id: "test_client_id"
    client-secret: "{noop}test_client_secret"

redis-mq:
#  cron: "*/1 * * * * *"
  cron: "-"
  scan-limit: 10
  queue:
    name: outbox-queue

jwt:
  header: Authorization
  secret: secret-jwt-code-item-[ogijhrg[aqghr]ihgaeiuhrg2jht89[4
  expiration-seconds: 600 # 10 mins

spring:
  redis:
    host: "localhost"
    port: 9999
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db?reWriteBatchedInserts=true
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: none
    show-sql: false