redis-mq:
#  cron: "-"
  cron: "*/1 * * * * *"
  scan-limit: 10
  queue:
    name: outbox-queue

security:
  oauth2:
    bit-bucket-oauth2:
      key: ${OPENID_BIT_BUCKET_OAUTH2_KEY}
      secret: ${OPENID_BIT_BUCKET_OAUTH2_SECRET}
    local-server:
      client-id: ${OPENID_SERVER_CUSTOM_CLIENT_ID}
      client-secret: ${OPENID_SERVER_CUSTOM_CLIENT_SECRET}
  jwt:
    header: AuthorizationJWT
    secret: ${JWT_SPRING_APPLICATION_CUSTOM_SECRET}
    expiration-seconds: 600 # 10 mins

management:
  endpoints:
    web:
      exposure:
        include: mappings

spring:
  redis:
    host: "localhost"
    port: 9999
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db?reWriteBatchedInserts=true
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: none
    show-sql: false
