server:
  port: 9000

user:
  oauth:
    clientName: customClient
    clientId: ${OPENID_SERVER_CUSTOM_CLIENT_ID}
    clientSecret: ${OPENID_SERVER_CUSTOM_CLIENT_SECRET}
    redirectUris: http://localhost:8080/login/oauth2/code/${user.oauth.clientName}
    user:
      username: user2
      password: user2
